"""
Seed 25 purchase orders across 90 days.

Distribution (matches spec):
    Draft             2
    Sent (ordered)    3
    Received         18
    Partial Receipt   2
    --------------------
    Total            25

Of the 25, 3 are tagged as 'Generated from Low Stock workflow' via
notes='LOW_STOCK_AUTO'. The low-stock raw materials (PLA-BLK + PLA-WHT
from inventory.py) are prioritized for those 3 so the UI shows the
Low Stock -> Auto-PO path.

Uses purchase_order_service.create_purchase_order for row creation so
PO-#### number generation and PurchasingEvent('created') entries fire.
Status transitions (ordered/received/partial) are applied via direct
ORM updates to skip the receive_purchase_order inventory roll-in
workflow -- that path consumes the PO into stock and we want the
seeded inventory state to stay as-is for screenshot stability.
"""
from datetime import date, timedelta
from decimal import Decimal
from typing import Any

from sqlalchemy.orm import Session

from app.models.purchase_order import PurchaseOrder, PurchaseOrderLine
from app.services import purchase_order_service

from scripts.seed_data import _time


DIST = [
    ("draft", 2),
    ("ordered", 3),
    ("received", 18),
    ("partial", 2),
]
LOW_STOCK_AUTO_POS = 3


def _make_lines(rng, raw_material_ids: list[int], raw_products: dict, priority_ids: list[int] | None = None) -> list[dict]:
    pool = priority_ids if priority_ids else raw_material_ids
    n = rng.randint(1, min(3, len(pool)))
    chosen = rng.sample(pool, k=n)
    lines = []
    for pid in chosen:
        product = raw_products[pid]
        purchase_qty = Decimal(str(rng.choice([1, 2, 3, 5])))
        unit_cost = product.standard_cost or Decimal("20.00")
        lines.append({
            "product_id": pid,
            "quantity_ordered": purchase_qty,
            "unit_cost": Decimal(str(unit_cost)),
            "purchase_unit": product.purchase_uom or "KG",
        })
    return lines


def seed(db: Session, context: dict[str, Any]) -> None:
    rng = _time.rng()
    now = _time.now()
    admin_id = context["admin_id"]
    admin_email = context["admin_email"]
    vendor_ids = context["vendor_ids"]
    raw_material_ids = context["raw_material_ids"]

    from app.models.product import Product
    raw_products = {p.id: p for p in db.query(Product).filter(Product.id.in_(raw_material_ids)).all()}

    low_stock_priority = [
        pid for pid, p in raw_products.items()
        if p.sku in ("RAW-PLA-BLK", "RAW-PLA-WHT")
    ]

    all_po_ids: list[int] = []
    po_ids_by_status: dict[str, list[int]] = {}

    auto_po_budget = LOW_STOCK_AUTO_POS

    for status_key, count in DIST:
        po_ids_by_status[status_key] = []
        for i in range(count):
            use_low_stock = auto_po_budget > 0 and rng.random() < 0.35
            if use_low_stock:
                lines = _make_lines(rng, raw_material_ids, raw_products, priority_ids=low_stock_priority)
                notes = "LOW_STOCK_AUTO: Generated by Low Stock workflow"
                auto_po_budget -= 1
            else:
                lines = _make_lines(rng, raw_material_ids, raw_products)
                notes = None

            days_back = rng.randint(5, 90) if status_key != "draft" else rng.randint(0, 3)
            order_date = (now - timedelta(days=days_back)).date()

            po = purchase_order_service.create_purchase_order(
                db,
                data={
                    "vendor_id": rng.choice(vendor_ids),
                    "order_date": order_date,
                    "expected_date": order_date + timedelta(days=rng.randint(5, 14)),
                    "shipping_cost": Decimal(str(rng.choice([0, 10, 15, 25]))),
                    "notes": notes,
                },
                lines_data=lines,
                created_by=admin_email,
                user_id=admin_id,
            )
            po.created_at = now - timedelta(days=days_back)
            po.updated_at = po.created_at
            all_po_ids.append(po.id)
            po_ids_by_status[status_key].append(po.id)

    db.flush()

    for po_id in po_ids_by_status["ordered"]:
        po = db.get(PurchaseOrder, po_id)
        po.status = "ordered"
        db.add(po)

    for po_id in po_ids_by_status["received"]:
        po = db.get(PurchaseOrder, po_id)
        po.status = "received"
        po.shipped_date = (po.order_date or now.date()) + timedelta(days=rng.randint(1, 5))
        po.received_date = po.shipped_date + timedelta(days=rng.randint(2, 8))
        for line in po.lines:
            line.quantity_received = line.quantity_ordered
        db.add(po)

    for po_id in po_ids_by_status["partial"]:
        po = db.get(PurchaseOrder, po_id)
        po.status = "ordered"
        po.shipped_date = (po.order_date or now.date()) + timedelta(days=rng.randint(1, 5))
        po.received_date = po.shipped_date + timedelta(days=rng.randint(1, 3))
        for line in po.lines:
            fraction = Decimal(str(rng.choice([0.3, 0.5, 0.7])))
            line.quantity_received = (line.quantity_ordered * fraction).quantize(Decimal("0.01"))
        db.add(po)

    db.flush()

    context["purchase_order_ids"] = all_po_ids
    auto_count = LOW_STOCK_AUTO_POS - auto_po_budget
    print(
        f"[seed]   {len(all_po_ids)} purchase orders "
        f"(2 draft / 3 ordered / 18 received / 2 partial, "
        f"{auto_count} from Low Stock workflow)"
    )
